# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'process_mainUI_003.ui'
#
# Created: Sun Dec 18 13:42:31 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

import process_tree_classes
#self.tree_tv = process_tree_classes.TreeTest(self.tab)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(773, 939)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_22 = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setTabShape(QtGui.QTabWidget.Triangular)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.tab)
        self.horizontalLayout_6.setSpacing(5)
        self.horizontalLayout_6.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setSpacing(5)
        self.verticalLayout_4.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtGui.QFrame(self.tab)
        self.frame.setMaximumSize(QtCore.QSize(400, 16777215))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.frame)
        self.horizontalLayout_7.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(2)
        self.horizontalLayout_4.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.horizontalLayout_4.setContentsMargins(1, -1, -1, -1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.new_tree_b = QtGui.QPushButton(self.frame)
        self.new_tree_b.setObjectName("new_tree_b")
        self.horizontalLayout_4.addWidget(self.new_tree_b)
        self.remove_tree_b = QtGui.QPushButton(self.frame)
        self.remove_tree_b.setObjectName("remove_tree_b")
        self.horizontalLayout_4.addWidget(self.remove_tree_b)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_4)
        self.verticalLayout_2.addWidget(self.frame)
        self.new_tree_le = QtGui.QLineEdit(self.tab)
        self.new_tree_le.setMaximumSize(QtCore.QSize(400, 16777215))
        self.new_tree_le.setObjectName("new_tree_le")
        self.verticalLayout_2.addWidget(self.new_tree_le)
        self.new_tree_lw = QtGui.QListWidget(self.tab)
        self.new_tree_lw.setMaximumSize(QtCore.QSize(400, 16777215))
        self.new_tree_lw.setObjectName("new_tree_lw")
        self.verticalLayout_2.addWidget(self.new_tree_lw)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.frame1 = QtGui.QFrame(self.tab)
        self.frame1.setMaximumSize(QtCore.QSize(400, 16777215))
        self.frame1.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame1.setFrameShadow(QtGui.QFrame.Raised)
        self.frame1.setObjectName("frame1")
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.frame1)
        self.horizontalLayout_8.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(2)
        self.horizontalLayout_5.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.horizontalLayout_5.setContentsMargins(1, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.new_variable_b = QtGui.QPushButton(self.frame1)
        self.new_variable_b.setObjectName("new_variable_b")
        self.horizontalLayout_5.addWidget(self.new_variable_b)
        self.remove_variable_b = QtGui.QPushButton(self.frame1)
        self.remove_variable_b.setObjectName("remove_variable_b")
        self.horizontalLayout_5.addWidget(self.remove_variable_b)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.horizontalLayout_8.addLayout(self.horizontalLayout_5)
        self.verticalLayout_3.addWidget(self.frame1)
        self.new_variabl_le = QtGui.QLineEdit(self.tab)
        self.new_variabl_le.setMaximumSize(QtCore.QSize(400, 16777215))
        self.new_variabl_le.setObjectName("new_variabl_le")
        self.verticalLayout_3.addWidget(self.new_variabl_le)
        self.new_variable_lw = QtGui.QListWidget(self.tab)
        self.new_variable_lw.setMaximumSize(QtCore.QSize(400, 16777215))
        self.new_variable_lw.setObjectName("new_variable_lw")
        self.verticalLayout_3.addWidget(self.new_variable_lw)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem3)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.horizontalLayout_6.addLayout(self.verticalLayout_4)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setSpacing(5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tree_name_label = QtGui.QLabel(self.tab)
        self.tree_name_label.setObjectName("tree_name_label")
        self.horizontalLayout_2.addWidget(self.tree_name_label)
        self.tree_name_label_2 = QtGui.QLabel(self.tab)
        self.tree_name_label_2.setObjectName("tree_name_label_2")
        self.horizontalLayout_2.addWidget(self.tree_name_label_2)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.frame_2 = QtGui.QFrame(self.tab)
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_9 = QtGui.QHBoxLayout(self.frame_2)
        self.horizontalLayout_9.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(5)
        self.horizontalLayout_3.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.save_tree_b = QtGui.QPushButton(self.frame_2)
        self.save_tree_b.setObjectName("save_tree_b")
        self.horizontalLayout_3.addWidget(self.save_tree_b)
        self.change_root_path_b = QtGui.QPushButton(self.frame_2)
        self.change_root_path_b.setObjectName("change_root_path_b")
        self.horizontalLayout_3.addWidget(self.change_root_path_b)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.horizontalLayout_9.addLayout(self.horizontalLayout_3)
        self.verticalLayout.addWidget(self.frame_2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.root_path_label = QtGui.QLabel(self.tab)
        self.root_path_label.setObjectName("root_path_label")
        self.horizontalLayout.addWidget(self.root_path_label)
        self.root_path_le = QtGui.QLineEdit(self.tab)
        self.root_path_le.setEnabled(True)
        self.root_path_le.setObjectName("root_path_le")
        self.horizontalLayout.addWidget(self.root_path_le)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.process_tv = process_tree_classes.TreeTest(self.tab)
        self.process_tv.setEnabled(True)
        self.process_tv.setObjectName("process_tv")
        self.verticalLayout.addWidget(self.process_tv)
        self.horizontalLayout_6.addLayout(self.verticalLayout)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.tab_2)
        self.verticalLayout_7.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_4 = QtGui.QFrame(self.tab_2)
        self.frame_4.setMaximumSize(QtCore.QSize(850, 16777215))
        self.frame_4.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_14 = QtGui.QHBoxLayout(self.frame_4)
        self.horizontalLayout_14.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_2 = QtGui.QLabel(self.frame_4)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_12.addWidget(self.label_2)
        self.key_te = QtGui.QLineEdit(self.frame_4)
        self.key_te.setObjectName("key_te")
        self.horizontalLayout_12.addWidget(self.key_te)
        self.horizontalLayout_14.addLayout(self.horizontalLayout_12)
        self.verticalLayout_5.addWidget(self.frame_4)
        self.frame_3 = QtGui.QFrame(self.tab_2)
        self.frame_3.setMaximumSize(QtCore.QSize(850, 16777215))
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_13 = QtGui.QHBoxLayout(self.frame_3)
        self.horizontalLayout_13.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.new_key_b = QtGui.QPushButton(self.frame_3)
        self.new_key_b.setObjectName("new_key_b")
        self.horizontalLayout_11.addWidget(self.new_key_b)
        self.delete_key_b = QtGui.QPushButton(self.frame_3)
        self.delete_key_b.setObjectName("delete_key_b")
        self.horizontalLayout_11.addWidget(self.delete_key_b)
        self.label = QtGui.QLabel(self.frame_3)
        self.label.setObjectName("label")
        self.horizontalLayout_11.addWidget(self.label)
        self.new_key_name_le = QtGui.QLineEdit(self.frame_3)
        self.new_key_name_le.setObjectName("new_key_name_le")
        self.horizontalLayout_11.addWidget(self.new_key_name_le)
        self.horizontalLayout_13.addLayout(self.horizontalLayout_11)
        self.verticalLayout_5.addWidget(self.frame_3)
        self.keys_tw = QtGui.QTableWidget(self.tab_2)
        self.keys_tw.setMaximumSize(QtCore.QSize(850, 16777215))
        self.keys_tw.setObjectName("keys_tw")
        self.keys_tw.setColumnCount(2)
        self.keys_tw.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.keys_tw.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.keys_tw.setHorizontalHeaderItem(1, item)
        self.verticalLayout_5.addWidget(self.keys_tw)
        self.verticalLayout_7.addLayout(self.verticalLayout_5)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame_5 = QtGui.QFrame(self.tab_2)
        self.frame_5.setMaximumSize(QtCore.QSize(850, 16777215))
        self.frame_5.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_15 = QtGui.QHBoxLayout(self.frame_5)
        self.horizontalLayout_15.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_3 = QtGui.QLabel(self.frame_5)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_16.addWidget(self.label_3)
        self.constant_te = QtGui.QLineEdit(self.frame_5)
        self.constant_te.setObjectName("constant_te")
        self.horizontalLayout_16.addWidget(self.constant_te)
        self.horizontalLayout_15.addLayout(self.horizontalLayout_16)
        self.constant_fiepath_te = QtGui.QPushButton(self.frame_5)
        self.constant_fiepath_te.setObjectName("constant_fiepath_te")
        self.horizontalLayout_15.addWidget(self.constant_fiepath_te)
        self.verticalLayout_6.addWidget(self.frame_5)
        self.frame_6 = QtGui.QFrame(self.tab_2)
        self.frame_6.setMaximumSize(QtCore.QSize(850, 16777215))
        self.frame_6.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_17 = QtGui.QHBoxLayout(self.frame_6)
        self.horizontalLayout_17.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.horizontalLayout_18 = QtGui.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.new_constant_b = QtGui.QPushButton(self.frame_6)
        self.new_constant_b.setObjectName("new_constant_b")
        self.horizontalLayout_18.addWidget(self.new_constant_b)
        self.delete_constant_b = QtGui.QPushButton(self.frame_6)
        self.delete_constant_b.setObjectName("delete_constant_b")
        self.horizontalLayout_18.addWidget(self.delete_constant_b)
        self.label_4 = QtGui.QLabel(self.frame_6)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_18.addWidget(self.label_4)
        self.new_constant_name_le = QtGui.QLineEdit(self.frame_6)
        self.new_constant_name_le.setObjectName("new_constant_name_le")
        self.horizontalLayout_18.addWidget(self.new_constant_name_le)
        self.horizontalLayout_17.addLayout(self.horizontalLayout_18)
        self.verticalLayout_6.addWidget(self.frame_6)
        self.constants_tw = QtGui.QTableWidget(self.tab_2)
        self.constants_tw.setMaximumSize(QtCore.QSize(850, 16777215))
        self.constants_tw.setObjectName("constants_tw")
        self.constants_tw.setColumnCount(2)
        self.constants_tw.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.constants_tw.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.constants_tw.setHorizontalHeaderItem(1, item)
        self.verticalLayout_6.addWidget(self.constants_tw)
        self.verticalLayout_7.addLayout(self.verticalLayout_6)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.tab_3)
        self.verticalLayout_10.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.frame_8 = QtGui.QFrame(self.tab_3)
        self.frame_8.setMaximumSize(QtCore.QSize(850, 80))
        self.frame_8.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_8.setLineWidth(2)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_26 = QtGui.QHBoxLayout(self.frame_8)
        self.horizontalLayout_26.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_25 = QtGui.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.new_process_b = QtGui.QPushButton(self.frame_8)
        self.new_process_b.setObjectName("new_process_b")
        self.horizontalLayout_25.addWidget(self.new_process_b)
        self.new_process_name_le = QtGui.QLineEdit(self.frame_8)
        self.new_process_name_le.setMinimumSize(QtCore.QSize(0, 20))
        self.new_process_name_le.setObjectName("new_process_name_le")
        self.horizontalLayout_25.addWidget(self.new_process_name_le)
        self.save_process_b = QtGui.QPushButton(self.frame_8)
        self.save_process_b.setObjectName("save_process_b")
        self.horizontalLayout_25.addWidget(self.save_process_b)
        self.load_process_b = QtGui.QPushButton(self.frame_8)
        self.load_process_b.setObjectName("load_process_b")
        self.horizontalLayout_25.addWidget(self.load_process_b)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_25.addItem(spacerItem6)
        self.verticalLayout_8.addLayout(self.horizontalLayout_25)
        self.current_process_le = QtGui.QLineEdit(self.frame_8)
        self.current_process_le.setObjectName("current_process_le")
        self.verticalLayout_8.addWidget(self.current_process_le)
        self.horizontalLayout_26.addLayout(self.verticalLayout_8)
        self.verticalLayout_10.addWidget(self.frame_8)
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.file_input_frame = QtGui.QFrame(self.tab_3)
        self.file_input_frame.setEnabled(False)
        self.file_input_frame.setMaximumSize(QtCore.QSize(850, 16777215))
        self.file_input_frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.file_input_frame.setFrameShadow(QtGui.QFrame.Raised)
        self.file_input_frame.setObjectName("file_input_frame")
        self.verticalLayout_15 = QtGui.QVBoxLayout(self.file_input_frame)
        self.verticalLayout_15.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.horizontalLayout_20 = QtGui.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.from_file_rb = QtGui.QRadioButton(self.file_input_frame)
        self.from_file_rb.setChecked(True)
        self.from_file_rb.setObjectName("from_file_rb")
        self.horizontalLayout_20.addWidget(self.from_file_rb)
        self.from_folder_rb = QtGui.QRadioButton(self.file_input_frame)
        self.from_folder_rb.setObjectName("from_folder_rb")
        self.horizontalLayout_20.addWidget(self.from_folder_rb)
        self.enter_values_rb = QtGui.QRadioButton(self.file_input_frame)
        self.enter_values_rb.setObjectName("enter_values_rb")
        self.horizontalLayout_20.addWidget(self.enter_values_rb)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem7)
        self.verticalLayout_15.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_19 = QtGui.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.set_file_input_le = QtGui.QLineEdit(self.file_input_frame)
        self.set_file_input_le.setObjectName("set_file_input_le")
        self.horizontalLayout_19.addWidget(self.set_file_input_le)
        self.set_file_input_b = QtGui.QPushButton(self.file_input_frame)
        self.set_file_input_b.setObjectName("set_file_input_b")
        self.horizontalLayout_19.addWidget(self.set_file_input_b)
        self.verticalLayout_15.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.set_folder_input_le = QtGui.QLineEdit(self.file_input_frame)
        self.set_folder_input_le.setObjectName("set_folder_input_le")
        self.horizontalLayout_10.addWidget(self.set_folder_input_le)
        self.set_folder_input_b = QtGui.QPushButton(self.file_input_frame)
        self.set_folder_input_b.setObjectName("set_folder_input_b")
        self.horizontalLayout_10.addWidget(self.set_folder_input_b)
        self.set_folder_input_cb = QtGui.QComboBox(self.file_input_frame)
        self.set_folder_input_cb.setObjectName("set_folder_input_cb")
        self.set_folder_input_cb.addItem("")
        self.set_folder_input_cb.addItem("")
        self.set_folder_input_cb.addItem("")
        self.horizontalLayout_10.addWidget(self.set_folder_input_cb)
        self.verticalLayout_15.addLayout(self.horizontalLayout_10)
        self.enter_values_te = QtGui.QPlainTextEdit(self.file_input_frame)
        self.enter_values_te.setObjectName("enter_values_te")
        self.verticalLayout_15.addWidget(self.enter_values_te)
        self.verticalLayout_9.addWidget(self.file_input_frame)
        self.verticalLayout_10.addLayout(self.verticalLayout_9)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setEnabled(False)
        self.tab_4.setObjectName("tab_4")
        self.horizontalLayout_28 = QtGui.QHBoxLayout(self.tab_4)
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.horizontalLayout_23 = QtGui.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.verticalLayout_11 = QtGui.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.verticalLayout_12 = QtGui.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.frame_7 = QtGui.QFrame(self.tab_4)
        self.frame_7.setMaximumSize(QtCore.QSize(500, 16777215))
        self.frame_7.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_13 = QtGui.QVBoxLayout(self.frame_7)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.show_all_vars_bc = QtGui.QCheckBox(self.frame_7)
        self.show_all_vars_bc.setChecked(True)
        self.show_all_vars_bc.setObjectName("show_all_vars_bc")
        self.verticalLayout_13.addWidget(self.show_all_vars_bc)
        self.filters_le = QtGui.QLineEdit(self.frame_7)
        self.filters_le.setMaximumSize(QtCore.QSize(500, 16777215))
        self.filters_le.setObjectName("filters_le")
        self.verticalLayout_13.addWidget(self.filters_le)
        self.verticalLayout_12.addWidget(self.frame_7)
        self.verticalLayout_11.addLayout(self.verticalLayout_12)
        self.widget = QtGui.QWidget(self.tab_4)
        self.widget.setMaximumSize(QtCore.QSize(500, 16777215))
        self.widget.setObjectName("widget")
        self.horizontalLayout_21 = QtGui.QHBoxLayout(self.widget)
        self.horizontalLayout_21.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_21.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.horizontalLayout_24 = QtGui.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.new_filter_b = QtGui.QPushButton(self.widget)
        self.new_filter_b.setMaximumSize(QtCore.QSize(80, 16777215))
        self.new_filter_b.setObjectName("new_filter_b")
        self.horizontalLayout_24.addWidget(self.new_filter_b)
        self.new_filter_cb = QtGui.QComboBox(self.widget)
        self.new_filter_cb.setMinimumSize(QtCore.QSize(200, 0))
        self.new_filter_cb.setObjectName("new_filter_cb")
        self.horizontalLayout_24.addWidget(self.new_filter_cb)
        self.refresh_filters_b = QtGui.QPushButton(self.widget)
        self.refresh_filters_b.setMaximumSize(QtCore.QSize(110, 16777215))
        self.refresh_filters_b.setObjectName("refresh_filters_b")
        self.horizontalLayout_24.addWidget(self.refresh_filters_b)
        spacerItem8 = QtGui.QSpacerItem(5, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_24.addItem(spacerItem8)
        self.horizontalLayout_21.addLayout(self.horizontalLayout_24)
        self.verticalLayout_11.addWidget(self.widget)
        self.filters_lw = QtGui.QListWidget(self.tab_4)
        self.filters_lw.setMaximumSize(QtCore.QSize(500, 16777215))
        self.filters_lw.setObjectName("filters_lw")
        self.verticalLayout_11.addWidget(self.filters_lw)
        self.horizontalLayout_23.addLayout(self.verticalLayout_11)
        self.horizontalLayout_28.addLayout(self.horizontalLayout_23)
        self.data_object_lw = QtGui.QListWidget(self.tab_4)
        self.data_object_lw.setObjectName("data_object_lw")
        self.horizontalLayout_28.addWidget(self.data_object_lw)
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setEnabled(False)
        self.tab_5.setObjectName("tab_5")
        self.verticalLayout_17 = QtGui.QVBoxLayout(self.tab_5)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.horizontalLayout_27 = QtGui.QHBoxLayout()
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.new_output_b = QtGui.QPushButton(self.tab_5)
        self.new_output_b.setMaximumSize(QtCore.QSize(100, 16777215))
        self.new_output_b.setObjectName("new_output_b")
        self.horizontalLayout_27.addWidget(self.new_output_b)
        self.new_output_cb = QtGui.QComboBox(self.tab_5)
        self.new_output_cb.setMinimumSize(QtCore.QSize(300, 0))
        self.new_output_cb.setObjectName("new_output_cb")
        self.horizontalLayout_27.addWidget(self.new_output_cb)
        self.refresh_outputs_b = QtGui.QPushButton(self.tab_5)
        self.refresh_outputs_b.setMaximumSize(QtCore.QSize(110, 16777215))
        self.refresh_outputs_b.setObjectName("refresh_outputs_b")
        self.horizontalLayout_27.addWidget(self.refresh_outputs_b)
        spacerItem9 = QtGui.QSpacerItem(10, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_27.addItem(spacerItem9)
        self.verticalLayout_17.addLayout(self.horizontalLayout_27)
        self.outputs_lw = QtGui.QListWidget(self.tab_5)
        self.outputs_lw.setObjectName("outputs_lw")
        self.verticalLayout_17.addWidget(self.outputs_lw)
        self.tabWidget.addTab(self.tab_5, "OUTPUTS")
        self.horizontalLayout_22.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar()
        self.menubar.setGeometry(QtCore.QRect(0, 0, 773, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.from_file_rb, QtCore.SIGNAL("clicked(bool)"), self.set_file_input_le.setEnabled)
        QtCore.QObject.connect(self.from_file_rb, QtCore.SIGNAL("clicked(bool)"), self.set_folder_input_le.setDisabled)
        QtCore.QObject.connect(self.from_file_rb, QtCore.SIGNAL("clicked(bool)"), self.enter_values_te.setDisabled)
        QtCore.QObject.connect(self.from_folder_rb, QtCore.SIGNAL("clicked(bool)"), self.set_file_input_le.setDisabled)
        QtCore.QObject.connect(self.from_folder_rb, QtCore.SIGNAL("clicked(bool)"), self.set_folder_input_le.setEnabled)
        QtCore.QObject.connect(self.from_folder_rb, QtCore.SIGNAL("clicked(bool)"), self.enter_values_te.setDisabled)
        QtCore.QObject.connect(self.enter_values_rb, QtCore.SIGNAL("clicked(bool)"), self.set_file_input_le.setDisabled)
        QtCore.QObject.connect(self.enter_values_rb, QtCore.SIGNAL("clicked(bool)"), self.set_folder_input_le.setDisabled)
        QtCore.QObject.connect(self.enter_values_rb, QtCore.SIGNAL("clicked(bool)"), self.enter_values_te.setEnabled)
        QtCore.QObject.connect(self.from_file_rb, QtCore.SIGNAL("clicked(bool)"), self.set_file_input_b.setEnabled)
        QtCore.QObject.connect(self.from_file_rb, QtCore.SIGNAL("clicked(bool)"), self.set_folder_input_b.setDisabled)
        QtCore.QObject.connect(self.from_file_rb, QtCore.SIGNAL("clicked(bool)"), self.set_folder_input_cb.setDisabled)
        QtCore.QObject.connect(self.from_file_rb, QtCore.SIGNAL("clicked(bool)"), self.enter_values_te.setDisabled)
        QtCore.QObject.connect(self.from_folder_rb, QtCore.SIGNAL("clicked(bool)"), self.set_folder_input_cb.setEnabled)
        QtCore.QObject.connect(self.from_folder_rb, QtCore.SIGNAL("clicked(bool)"), self.set_file_input_b.setDisabled)
        QtCore.QObject.connect(self.enter_values_rb, QtCore.SIGNAL("clicked(bool)"), self.set_folder_input_b.setDisabled)
        QtCore.QObject.connect(self.enter_values_rb, QtCore.SIGNAL("clicked(bool)"), self.set_folder_input_cb.setDisabled)
        QtCore.QObject.connect(self.enter_values_rb, QtCore.SIGNAL("clicked(bool)"), self.set_file_input_b.setDisabled)
        QtCore.QObject.connect(self.from_folder_rb, QtCore.SIGNAL("clicked(bool)"), self.set_file_input_b.setDisabled)
        QtCore.QObject.connect(self.from_folder_rb, QtCore.SIGNAL("clicked(bool)"), self.set_folder_input_b.setEnabled)
        QtCore.QObject.connect(self.from_folder_rb, QtCore.SIGNAL("clicked(bool)"), self.set_folder_input_cb.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.new_tree_b.setText(QtGui.QApplication.translate("MainWindow", "new Tree", None, QtGui.QApplication.UnicodeUTF8))
        self.remove_tree_b.setText(QtGui.QApplication.translate("MainWindow", "remove Tree", None, QtGui.QApplication.UnicodeUTF8))
        self.new_variable_b.setText(QtGui.QApplication.translate("MainWindow", "new Variable", None, QtGui.QApplication.UnicodeUTF8))
        self.remove_variable_b.setText(QtGui.QApplication.translate("MainWindow", "remove Variable", None, QtGui.QApplication.UnicodeUTF8))
        self.tree_name_label.setText(QtGui.QApplication.translate("MainWindow", "name:", None, QtGui.QApplication.UnicodeUTF8))
        self.tree_name_label_2.setText(QtGui.QApplication.translate("MainWindow", "none", None, QtGui.QApplication.UnicodeUTF8))
        self.save_tree_b.setText(QtGui.QApplication.translate("MainWindow", "save tree", None, QtGui.QApplication.UnicodeUTF8))
        self.change_root_path_b.setText(QtGui.QApplication.translate("MainWindow", "change root path", None, QtGui.QApplication.UnicodeUTF8))
        self.root_path_label.setText(QtGui.QApplication.translate("MainWindow", "root path:", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("MainWindow", "TREES", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "key:", None, QtGui.QApplication.UnicodeUTF8))
        self.new_key_b.setText(QtGui.QApplication.translate("MainWindow", "new key", None, QtGui.QApplication.UnicodeUTF8))
        self.delete_key_b.setText(QtGui.QApplication.translate("MainWindow", "delete key", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "name:", None, QtGui.QApplication.UnicodeUTF8))
        self.keys_tw.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("MainWindow", "NAME", None, QtGui.QApplication.UnicodeUTF8))
        self.keys_tw.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("MainWindow", "KEY", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "constant:", None, QtGui.QApplication.UnicodeUTF8))
        self.constant_fiepath_te.setText(QtGui.QApplication.translate("MainWindow", "filepath", None, QtGui.QApplication.UnicodeUTF8))
        self.new_constant_b.setText(QtGui.QApplication.translate("MainWindow", "new constant", None, QtGui.QApplication.UnicodeUTF8))
        self.delete_constant_b.setText(QtGui.QApplication.translate("MainWindow", "delete constant", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "name:", None, QtGui.QApplication.UnicodeUTF8))
        self.constants_tw.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("MainWindow", "NAME", None, QtGui.QApplication.UnicodeUTF8))
        self.constants_tw.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("MainWindow", "CONSTANT", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("MainWindow", "KEYS", None, QtGui.QApplication.UnicodeUTF8))
        self.new_process_b.setText(QtGui.QApplication.translate("MainWindow", "New Process", None, QtGui.QApplication.UnicodeUTF8))
        self.save_process_b.setText(QtGui.QApplication.translate("MainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.load_process_b.setText(QtGui.QApplication.translate("MainWindow", "Load", None, QtGui.QApplication.UnicodeUTF8))
        self.from_file_rb.setText(QtGui.QApplication.translate("MainWindow", "from file", None, QtGui.QApplication.UnicodeUTF8))
        self.from_folder_rb.setText(QtGui.QApplication.translate("MainWindow", "from folder", None, QtGui.QApplication.UnicodeUTF8))
        self.enter_values_rb.setText(QtGui.QApplication.translate("MainWindow", "enter values", None, QtGui.QApplication.UnicodeUTF8))
        self.set_file_input_b.setText(QtGui.QApplication.translate("MainWindow", "set file", None, QtGui.QApplication.UnicodeUTF8))
        self.set_folder_input_b.setText(QtGui.QApplication.translate("MainWindow", "set folder", None, QtGui.QApplication.UnicodeUTF8))
        self.set_folder_input_cb.setItemText(0, QtGui.QApplication.translate("MainWindow", "files", None, QtGui.QApplication.UnicodeUTF8))
        self.set_folder_input_cb.setItemText(1, QtGui.QApplication.translate("MainWindow", "folders", None, QtGui.QApplication.UnicodeUTF8))
        self.set_folder_input_cb.setItemText(2, QtGui.QApplication.translate("MainWindow", "files recursive", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QtGui.QApplication.translate("MainWindow", "PROJECT", None, QtGui.QApplication.UnicodeUTF8))
        self.show_all_vars_bc.setText(QtGui.QApplication.translate("MainWindow", "show all enteries", None, QtGui.QApplication.UnicodeUTF8))
        self.new_filter_b.setText(QtGui.QApplication.translate("MainWindow", "New Filter", None, QtGui.QApplication.UnicodeUTF8))
        self.refresh_filters_b.setText(QtGui.QApplication.translate("MainWindow", "Refresh Filters", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), QtGui.QApplication.translate("MainWindow", "FILTERS", None, QtGui.QApplication.UnicodeUTF8))
        self.new_output_b.setText(QtGui.QApplication.translate("MainWindow", "New Output", None, QtGui.QApplication.UnicodeUTF8))
        self.refresh_outputs_b.setText(QtGui.QApplication.translate("MainWindow", "Refresh Filters", None, QtGui.QApplication.UnicodeUTF8))

